before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/lxc-compose
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# brews:
#   - name: proxmox-lxc-compose
#     tap:
#       owner: larkinwc
#       name: homebrew-tap
#     folder: Formula
#     homepage: "https://github.com/larkinwc/proxmox-lxc-compose"
#     description: "A docker-compose like tool for managing LXC containers in Proxmox"
#     license: "MIT"
#     test: |
#       system "#{bin}/lxc-compose --version"
#     install: |
#       bin.install "lxc-compose"

dockers:
  - image_templates:
      - "ghcr.io/larkinwc/proxmox-lxc-compose:{{ .Version }}"
      - "ghcr.io/larkinwc/proxmox-lxc-compose:v{{ .Major }}"
      - "ghcr.io/larkinwc/proxmox-lxc-compose:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/larkinwc/proxmox-lxc-compose:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=A docker-compose like tool for managing LXC containers in Proxmox"
      - "--label=org.opencontainers.image.url=https://github.com/larkinwc/proxmox-lxc-compose"
      - "--label=org.opencontainers.image.source=https://github.com/larkinwc/proxmox-lxc-compose"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"