package oci

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DistroFamily inspects an extracted rootfs and returns a coarse distro family
// ("alpine", "debian", or "unknown") based on /etc/os-release.
func DistroFamily(rootfs string) string {
	data, err := os.ReadFile(filepath.Join(rootfs, "etc", "os-release"))
	if err != nil {
		return "unknown"
	}
	content := strings.ToLower(string(data))
	switch {
	case strings.Contains(content, "alpine"):
		return "alpine"
	case strings.Contains(content, "debian"), strings.Contains(content, "ubuntu"):
		return "debian"
	default:
		return "unknown"
	}
}

// FixLogSymlinks replaces symlinks under /var/log that point at /dev/stdout or
// /dev/stderr (the common OCI logging pattern) with empty regular files.
//
// In an unprivileged LXC container those device targets are not writable the
// way they are under Docker, which causes daemons like nginx to abort with
// "Permission denied". Returns the number of symlinks rewritten.
func FixLogSymlinks(rootfs string) (int, error) {
	logDir := filepath.Join(rootfs, "var", "log")
	count := 0

	err := filepath.Walk(logDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			// /var/log may not exist; that's fine.
			if os.IsNotExist(err) {
				return filepath.SkipDir
			}
			return err
		}
		if info.Mode()&os.ModeSymlink == 0 {
			return nil
		}
		target, err := os.Readlink(path)
		if err != nil {
			return nil // skip unreadable links
		}
		if target != "/dev/stdout" && target != "/dev/stderr" {
			return nil
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("failed to remove log symlink %s: %w", path, err)
		}
		f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			return fmt.Errorf("failed to create log file %s: %w", path, err)
		}
		_ = f.Close()
		count++
		return nil
	})
	if err != nil && !os.IsNotExist(err) {
		return count, err
	}
	return count, nil
}

// WriteNetworkConfig writes a DHCP network configuration for eth0 into the
// rootfs so that, when booted with the distro's own init, the primary
// interface comes up automatically. This is the documented fallback for the
// init-command mechanism. Returns the path written (relative to rootfs).
func WriteNetworkConfig(rootfs string, distro string) (string, error) {
	switch distro {
	case "alpine", "debian", "unknown":
		// Both Alpine (ifupdown) and Debian use /etc/network/interfaces.
		dir := filepath.Join(rootfs, "etc", "network")
		if err := os.MkdirAll(dir, 0755); err != nil {
			return "", fmt.Errorf("failed to create network dir: %w", err)
		}
		path := filepath.Join(dir, "interfaces")
		content := "auto lo\niface lo inet loopback\n\nauto eth0\niface eth0 inet dhcp\n"
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return "", fmt.Errorf("failed to write interfaces file: %w", err)
		}
		return filepath.Join("etc", "network", "interfaces"), nil
	default:
		return "", nil
	}
}

// shellQuote single-quotes a string for safe embedding in a /bin/sh command.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// buildExecLine combines an entrypoint and command into a single shell exec
// line with each argument individually quoted.
func buildExecLine(entrypoint, cmd []string) string {
	args := make([]string, 0, len(entrypoint)+len(cmd))
	args = append(args, entrypoint...)
	args = append(args, cmd...)
	if len(args) == 0 {
		return ""
	}
	quoted := make([]string, len(args))
	for i, a := range args {
		quoted[i] = shellQuote(a)
	}
	return "exec " + strings.Join(quoted, " ")
}

// InitWrapperPath is the in-container path of the generated init wrapper.
const InitWrapperPath = "/usr/local/bin/lxc-compose-init.sh"

// WriteInitWrapper writes a small POSIX shell init wrapper into the rootfs. The
// wrapper brings up eth0 via DHCP (best effort across busybox/dhclient) and
// then execs the image's original entrypoint+command, reproducing the Docker
// run semantics under LXC. Returns the in-container wrapper path.
//
// If the image declares no command, no wrapper is written and an empty path is
// returned (the container will boot the distro's normal init).
func WriteInitWrapper(rootfs string, entrypoint, cmd []string) (string, error) {
	execLine := buildExecLine(entrypoint, cmd)
	if execLine == "" {
		return "", nil
	}

	script := `#!/bin/sh
# Generated by lxc-compose: reproduces the OCI image's runtime under LXC.
# PVE plumbs eth0 into the container netns asynchronously, so wait for it to
# appear (bounded) before bringing it up; then exec the image command.
i=0
while [ $i -lt 50 ]; do
	[ -e /sys/class/net/eth0 ] && break
	i=$((i + 1))
	sleep 0.1
done
ip link set eth0 up 2>/dev/null || true
if command -v udhcpc >/dev/null 2>&1; then
	udhcpc -i eth0 -t 5 -n 2>/dev/null || true
elif command -v dhclient >/dev/null 2>&1; then
	dhclient eth0 2>/dev/null || true
fi
` + execLine + "\n"

	binDir := filepath.Join(rootfs, "usr", "local", "bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create wrapper dir: %w", err)
	}
	path := filepath.Join(binDir, "lxc-compose-init.sh")
	if err := os.WriteFile(path, []byte(script), 0755); err != nil {
		return "", fmt.Errorf("failed to write init wrapper: %w", err)
	}
	return InitWrapperPath, nil
}

// PostProcessResult summarizes the rootfs mutations applied during conversion.
type PostProcessResult struct {
	Distro          string
	LogLinksFixed   int
	NetworkConfig   string
	InitWrapperPath string
}

// PostProcessRootfs applies all OCI->LXC compatibility fixes to an extracted
// rootfs directory and returns a summary. entrypoint/cmd come from the image's
// inspected configuration.
func PostProcessRootfs(rootfs string, entrypoint, cmd []string) (PostProcessResult, error) {
	var res PostProcessResult
	res.Distro = DistroFamily(rootfs)

	fixed, err := FixLogSymlinks(rootfs)
	if err != nil {
		return res, err
	}
	res.LogLinksFixed = fixed

	netPath, err := WriteNetworkConfig(rootfs, res.Distro)
	if err != nil {
		return res, err
	}
	res.NetworkConfig = netPath

	wrapper, err := WriteInitWrapper(rootfs, entrypoint, cmd)
	if err != nil {
		return res, err
	}
	res.InitWrapperPath = wrapper

	return res, nil
}
