package oci

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// RuntimeConfig is the effective process configuration baked into a template.
type RuntimeConfig struct {
	Entrypoint  []string
	Command     []string
	Environment map[string]string
	WorkingDir  string
	Network     []RuntimeNetwork
}

// RuntimeNetwork describes guest interface startup performed before the process.
type RuntimeNetwork struct {
	Name    string
	IP      string
	Gateway string
	DHCP    bool
}

// RuntimeOverrides uses nil to inherit and a non-nil empty slice to clear.
// Environment is canonical and takes precedence over the Env alias.
type RuntimeOverrides struct {
	Entrypoint  []string
	Command     []string
	Env         map[string]string
	Environment map[string]string
}

// Validate rejects values that cannot be represented safely in a POSIX process.
func (o RuntimeOverrides) Validate() error {
	return validateRuntime(RuntimeConfig{Entrypoint: o.Entrypoint, Command: o.Command, Environment: o.Env}, o.Environment)
}

func validateRuntime(c RuntimeConfig, extra map[string]string) error {
	for _, args := range [][]string{c.Entrypoint, c.Command} {
		for _, arg := range args {
			if strings.ContainsRune(arg, 0) {
				return fmt.Errorf("process argument contains NUL")
			}
		}
	}
	if strings.ContainsRune(c.WorkingDir, 0) {
		return fmt.Errorf("working directory contains NUL")
	}
	for _, iface := range c.Network {
		if iface.Name == "" {
			return fmt.Errorf("empty network interface name")
		}
		for _, ch := range iface.Name {
			if !(ch >= 'a' && ch <= 'z') && !(ch >= 'A' && ch <= 'Z') && !(ch >= '0' && ch <= '9') && ch != '_' && ch != '-' && ch != '.' {
				return fmt.Errorf("invalid network interface %q", iface.Name)
			}
		}
		if iface.IP != "" && iface.IP != "manual" && !iface.DHCP {
			if _, _, err := net.ParseCIDR(iface.IP); err != nil && net.ParseIP(iface.IP) == nil {
				return fmt.Errorf("invalid interface IP %q", iface.IP)
			}
		}
		if iface.Gateway != "" && net.ParseIP(iface.Gateway) == nil {
			return fmt.Errorf("invalid gateway %q", iface.Gateway)
		}
	}
	for _, vars := range []map[string]string{c.Environment, extra} {
		for key, value := range vars {
			if key == "" {
				return fmt.Errorf("empty environment identifier")
			}
			for i, ch := range key {
				if ch != '_' && !(ch >= 'a' && ch <= 'z') && !(ch >= 'A' && ch <= 'Z') && !(i > 0 && ch >= '0' && ch <= '9') {
					return fmt.Errorf("invalid environment identifier %q", key)
				}
			}
			if strings.ContainsRune(value, 0) {
				return fmt.Errorf("environment value for %q contains NUL", key)
			}
		}
	}
	return nil
}

// ResolveRuntime implements Compose entrypoint/command inheritance and env precedence.
func ResolveRuntime(defaults RuntimeConfig, overrides RuntimeOverrides) (RuntimeConfig, error) {
	if err := overrides.Validate(); err != nil {
		return RuntimeConfig{}, err
	}
	if err := validateRuntime(defaults, nil); err != nil {
		return RuntimeConfig{}, err
	}
	result := defaults
	if overrides.Entrypoint != nil {
		result.Entrypoint = overrides.Entrypoint
		result.Command = nil // an explicit entrypoint suppresses the image Cmd
	}
	if overrides.Command != nil {
		result.Command = overrides.Command
	}
	result.Environment = make(map[string]string, len(defaults.Environment)+len(overrides.Env)+len(overrides.Environment))
	for _, vars := range []map[string]string{defaults.Environment, overrides.Env, overrides.Environment} {
		for key, value := range vars {
			result.Environment[key] = value
		}
	}
	return result, nil
}

// InitWrapperPath is the in-container path of the generated init wrapper.
const InitWrapperPath = "/usr/local/bin/lxc-compose-init.sh"

// WriteInitWrapper writes the effective process into a quoted POSIX shell wrapper.
// With only environment overrides, distro init remains the process that is exec'd.
func WriteInitWrapper(rootfs string, runtime RuntimeConfig) (string, error) {
	if err := validateRuntime(runtime, nil); err != nil {
		return "", err
	}
	entrypoint := runtime.Entrypoint
	nativeInit := len(entrypoint) == 0 && len(runtime.Command) == 0
	if nativeInit && len(runtime.Environment) == 0 && runtime.WorkingDir == "" {
		return "", nil
	}
	if nativeInit {
		entrypoint = []string{"/sbin/init"}
	}
	var script strings.Builder
	script.WriteString("#!/bin/sh\n# Generated by lxc-compose. Bring up the guest network, then replace PID 1.\nip link set lo up 2>/dev/null || true\n")
	network := runtime.Network
	if network == nil {
		network = []RuntimeNetwork{{Name: "eth0", DHCP: true}}
	}
	for _, iface := range network {
		name := shellQuote(iface.Name)
		script.WriteString("i=0\nwhile [ $i -lt 50 ]; do\n\t[ -e " + shellQuote("/sys/class/net/"+iface.Name) + " ] && break\n\ti=$((i + 1))\n\tsleep 0.1\ndone\n")
		script.WriteString("ip link set " + name + " up 2>/dev/null || true\n")
		if iface.DHCP {
			script.WriteString("if command -v udhcpc >/dev/null 2>&1; then\n\tudhcpc -i " + name + " -t 5 -n 2>/dev/null || true\nelif command -v dhclient >/dev/null 2>&1; then\n\tdhclient " + name + " 2>/dev/null || true\nfi\n")
		} else {
			if iface.IP != "" && iface.IP != "manual" {
				script.WriteString("ip addr replace " + shellQuote(iface.IP) + " dev " + name + " || exit 1\n")
			}
			if iface.Gateway != "" {
				script.WriteString("ip route replace default via " + shellQuote(iface.Gateway) + " dev " + name + " || exit 1\n")
			}
		}
	}
	keys := make([]string, 0, len(runtime.Environment))
	for key := range runtime.Environment {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		script.WriteString("export " + key + "=" + shellQuote(runtime.Environment[key]) + "\n")
	}
	if nativeInit && len(keys) > 0 {
		if err := writeSystemdEnvironment(rootfs, runtime.Environment, keys); err != nil {
			return "", err
		}
	}
	if runtime.WorkingDir != "" {
		script.WriteString("cd " + shellQuote(runtime.WorkingDir) + " || exit 1\n")
	}
	script.WriteString("exec")
	for _, args := range [2][]string{entrypoint, runtime.Command} {
		for _, arg := range args {
			script.WriteByte(' ')
			script.WriteString(shellQuote(arg))
		}
	}
	script.WriteString("\n")
	path, err := guestPath(rootfs, InitWrapperPath)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return "", fmt.Errorf("create wrapper directory: %w", err)
	}
	if err := os.WriteFile(path, []byte(script.String()), 0700); err != nil {
		return "", fmt.Errorf("write init wrapper: %w", err)
	}
	if err := os.Chmod(path, 0700); err != nil {
		return "", err
	}
	return InitWrapperPath, nil
}

// Systemd sanitizes its own environment and does not pass arbitrary inherited
// variables to system services. DefaultEnvironment applies them to actual units.
func writeSystemdEnvironment(rootfs string, environment map[string]string, keys []string) error {
	init, err := guestPath(rootfs, "/sbin/init")
	if err != nil {
		return err
	}
	if filepath.Base(init) != "systemd" {
		return nil
	}
	var config strings.Builder
	config.WriteString("[Manager]\nDefaultEnvironment=")
	for _, key := range keys {
		config.WriteByte(' ')
		config.WriteString(strconv.Quote(strings.ReplaceAll(key+"="+environment[key], "%", "%%")))
	}
	config.WriteString("\n")
	path, err := guestPath(rootfs, "/etc/systemd/system.conf.d/lxc-compose-environment.conf")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(config.String()), 0600); err != nil {
		return err
	}
	return os.Chmod(path, 0600)
}
