version: "1.0"
services:
  nginx-alpine:
    image: alpine:3.19
    security:
      isolation: strict
      apparmor_profile: lxc-container-default-restricted
      capabilities:
        - NET_BIND_SERVICE  # Required for nginx to bind to port 80
    cpu:
      cores: 1
      shares: 512
    memory:
      limit: 256M
      swap: 128M
    network:
      type: bridge
      bridge: vmbr0
      ip: dhcp  # Using DHCP for automatic IP assignment
      ports:
        - "80:80"  # Expose nginx HTTP port
    storage:
      root: 2G  # Alpine is very small, 2G is plenty
    environment:
      TZ: UTC
    command: ["/bin/sh", "-c", "apk add --no-cache nginx && nginx -g 'daemon off;'"]  # Install and run nginx
    # Alternatively, you could use a startup script:
    # command: ["/bin/sh", "-c", "apk add --no-cache nginx && mkdir -p /run/nginx && nginx -g 'daemon off;'"] 